# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmskinastani', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('num_oscars', models.IntegerField(default=0)),
                ('num_gramys', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmskinastani.Movie')),
            ],
        ),
    ]
