# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmskinastani', '0002_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='festivals',
        ),
        migrations.AddField(
            model_name='festival',
            name='movies',
            field=models.ManyToManyField(to='filmskinastani.Movie'),
        ),
    ]
