# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmskinastani', '0003_auto_20170717_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_award', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('number_films', models.IntegerField(default=0)),
                ('number_awards', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('awards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmskinastani.Award')),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.IntegerField(),
        ),
    ]
