# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmskinastani', '0007_auto_20170924_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='festival',
        ),
        migrations.AddField(
            model_name='festival',
            name='awards',
            field=models.ManyToManyField(to='filmskinastani.Award'),
        ),
    ]
