# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmskinastani', '0008_auto_20170924_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmskinastani.Award'),
        ),
        migrations.AlterField(
            model_name='producent',
            name='award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmskinastani.Award'),
        ),
    ]
